spring:
  datasource:
    url: jdbc:h2:mem:testusuario
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 5
        max-idle: 2
        min-idle: 1
      shutdown-timeout: 500